<p>Domestic Shipping Policy<br>
  For fast and reliable shipping, we exclusively ship through FedEx and USPS carrier service. Orders are shipped usually in 1 business day but we do reserve the right to take up to 2 business days for processing before shipping out. The delivery times stated only reflect the transit time and do not include the order processing time. Please note UPS ground / Standard does not deliver on Saturday, Sunday, or holidays. USPS does not deliver on Sundays and national holidays. XPRITE does not ship on Sunday and holidays.</p>
<p>We package all of our orders in either envelop or standard FedEx brown boxes and USPS Priority Mail Packaging. If the order is particularly fragile, we may use stickers or tape indicating FRAGILE if required.</p>
<p>USPS First Class &amp; Priority Mail Shipping Service<br>
  USPS first class service and Priority Mail is the fastest, most reliable shipping method for lightweight products. Every order is given a delivery confirmation number, allowing you to follow your package via the USPS website. The average parcel spends less than 48 hours in transit, and deliveries are made every day except Sunday. USPS will deliver to every address in the United States including PO Box, APO/FPO. For lighter and smaller packages, Xprite USA may choose to ship via USPS to ensure faster delivery. Refer to the map below for a detailed estimate of transit time using First Class or USPS Priority shipping.</p>
<p>For all other orders, refer to the table below for guideline. It will be mainly determined by the weight of the item.</p>
<p>UPS Shipping Service<br>
  Orders shipped thru UPS Ground will be given a delivery confirmation number allowing you to follow your package via the UPS Website. All packages are routinely delivered within 3-7 business days. For a more detailed estimation, refer to UPS Shipping Map located below. Please note that these are only approximate UPS delivery times, as provided to us by UPS. For guaranteed delivery time ask for UPS Next Day Air or UPS 2nd Day Air shipping. UPS does not ship to PO Boxes.</p>
<p>Additional Notes<br>
  If the wrong information is provided (address, phone, email) and results in your shipment being undeliverable, the customer is responsible for the shipping cost for the 2nd shipment.</p>
