/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50726
Source Host           : localhost:3306
Source Database       : zencart158a_com

Target Server Type    : MYSQL
Target Server Version : 50726
File Encoding         : 65001

Date: 2024-03-26 06:08:38
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `zones`
-- ----------------------------
DROP TABLE IF EXISTS `zones`;
CREATE TABLE `zones` (
  `zone_id` int(11) NOT NULL AUTO_INCREMENT,
  `zone_country_id` int(11) NOT NULL DEFAULT '0',
  `zone_code` varchar(32) NOT NULL DEFAULT '',
  `zone_name` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`zone_id`),
  KEY `idx_zone_country_id_zen` (`zone_country_id`),
  KEY `idx_zone_code_zen` (`zone_code`)
) ENGINE=MyISAM AUTO_INCREMENT=300 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of zen_zones
-- ----------------------------
INSERT INTO `zones` VALUES ('1', '223', 'AL', 'Alabama');
INSERT INTO `zones` VALUES ('2', '223', 'AK', 'Alaska');
INSERT INTO `zones` VALUES ('3', '223', 'AS', 'American Samoa');
INSERT INTO `zones` VALUES ('4', '223', 'AZ', 'Arizona');
INSERT INTO `zones` VALUES ('5', '223', 'AR', 'Arkansas');
INSERT INTO `zones` VALUES ('7', '223', 'AA', 'Armed Forces Americas');
INSERT INTO `zones` VALUES ('9', '223', 'AE', 'Armed Forces Europe');
INSERT INTO `zones` VALUES ('11', '223', 'AP', 'Armed Forces Pacific');
INSERT INTO `zones` VALUES ('12', '223', 'CA', 'California');
INSERT INTO `zones` VALUES ('13', '223', 'CO', 'Colorado');
INSERT INTO `zones` VALUES ('14', '223', 'CT', 'Connecticut');
INSERT INTO `zones` VALUES ('15', '223', 'DE', 'Delaware');
INSERT INTO `zones` VALUES ('16', '223', 'DC', 'District of Columbia');
INSERT INTO `zones` VALUES ('17', '223', 'FM', 'Federated States Of Micronesia');
INSERT INTO `zones` VALUES ('18', '223', 'FL', 'Florida');
INSERT INTO `zones` VALUES ('19', '223', 'GA', 'Georgia');
INSERT INTO `zones` VALUES ('20', '223', 'GU', 'Guam');
INSERT INTO `zones` VALUES ('21', '223', 'HI', 'Hawaii');
INSERT INTO `zones` VALUES ('22', '223', 'ID', 'Idaho');
INSERT INTO `zones` VALUES ('23', '223', 'IL', 'Illinois');
INSERT INTO `zones` VALUES ('24', '223', 'IN', 'Indiana');
INSERT INTO `zones` VALUES ('25', '223', 'IA', 'Iowa');
INSERT INTO `zones` VALUES ('26', '223', 'KS', 'Kansas');
INSERT INTO `zones` VALUES ('27', '223', 'KY', 'Kentucky');
INSERT INTO `zones` VALUES ('28', '223', 'LA', 'Louisiana');
INSERT INTO `zones` VALUES ('29', '223', 'ME', 'Maine');
INSERT INTO `zones` VALUES ('30', '223', 'MH', 'Marshall Islands');
INSERT INTO `zones` VALUES ('31', '223', 'MD', 'Maryland');
INSERT INTO `zones` VALUES ('32', '223', 'MA', 'Massachusetts');
INSERT INTO `zones` VALUES ('33', '223', 'MI', 'Michigan');
INSERT INTO `zones` VALUES ('34', '223', 'MN', 'Minnesota');
INSERT INTO `zones` VALUES ('35', '223', 'MS', 'Mississippi');
INSERT INTO `zones` VALUES ('36', '223', 'MO', 'Missouri');
INSERT INTO `zones` VALUES ('37', '223', 'MT', 'Montana');
INSERT INTO `zones` VALUES ('38', '223', 'NE', 'Nebraska');
INSERT INTO `zones` VALUES ('39', '223', 'NV', 'Nevada');
INSERT INTO `zones` VALUES ('40', '223', 'NH', 'New Hampshire');
INSERT INTO `zones` VALUES ('41', '223', 'NJ', 'New Jersey');
INSERT INTO `zones` VALUES ('42', '223', 'NM', 'New Mexico');
INSERT INTO `zones` VALUES ('43', '223', 'NY', 'New York');
INSERT INTO `zones` VALUES ('44', '223', 'NC', 'North Carolina');
INSERT INTO `zones` VALUES ('45', '223', 'ND', 'North Dakota');
INSERT INTO `zones` VALUES ('46', '223', 'MP', 'Northern Mariana Islands');
INSERT INTO `zones` VALUES ('47', '223', 'OH', 'Ohio');
INSERT INTO `zones` VALUES ('48', '223', 'OK', 'Oklahoma');
INSERT INTO `zones` VALUES ('49', '223', 'OR', 'Oregon');
INSERT INTO `zones` VALUES ('50', '163', 'PW', 'Palau');
INSERT INTO `zones` VALUES ('51', '223', 'PA', 'Pennsylvania');
INSERT INTO `zones` VALUES ('52', '223', 'PR', 'Puerto Rico');
INSERT INTO `zones` VALUES ('53', '223', 'RI', 'Rhode Island');
INSERT INTO `zones` VALUES ('54', '223', 'SC', 'South Carolina');
INSERT INTO `zones` VALUES ('55', '223', 'SD', 'South Dakota');
INSERT INTO `zones` VALUES ('56', '223', 'TN', 'Tennessee');
INSERT INTO `zones` VALUES ('57', '223', 'TX', 'Texas');
INSERT INTO `zones` VALUES ('58', '223', 'UT', 'Utah');
INSERT INTO `zones` VALUES ('59', '223', 'VT', 'Vermont');
INSERT INTO `zones` VALUES ('60', '223', 'VI', 'Virgin Islands');
INSERT INTO `zones` VALUES ('61', '223', 'VA', 'Virginia');
INSERT INTO `zones` VALUES ('62', '223', 'WA', 'Washington');
INSERT INTO `zones` VALUES ('63', '223', 'WV', 'West Virginia');
INSERT INTO `zones` VALUES ('64', '223', 'WI', 'Wisconsin');
INSERT INTO `zones` VALUES ('65', '223', 'WY', 'Wyoming');
INSERT INTO `zones` VALUES ('66', '38', 'AB', 'Alberta');
INSERT INTO `zones` VALUES ('67', '38', 'BC', 'British Columbia');
INSERT INTO `zones` VALUES ('68', '38', 'MB', 'Manitoba');
INSERT INTO `zones` VALUES ('69', '38', 'NL', 'Newfoundland');
INSERT INTO `zones` VALUES ('70', '38', 'NB', 'New Brunswick');
INSERT INTO `zones` VALUES ('71', '38', 'NS', 'Nova Scotia');
INSERT INTO `zones` VALUES ('72', '38', 'NT', 'Northwest Territories');
INSERT INTO `zones` VALUES ('73', '38', 'NU', 'Nunavut');
INSERT INTO `zones` VALUES ('74', '38', 'ON', 'Ontario');
INSERT INTO `zones` VALUES ('75', '38', 'PE', 'Prince Edward Island');
INSERT INTO `zones` VALUES ('76', '38', 'QC', 'Quebec');
INSERT INTO `zones` VALUES ('77', '38', 'SK', 'Saskatchewan');
INSERT INTO `zones` VALUES ('78', '38', 'YT', 'Yukon Territory');
INSERT INTO `zones` VALUES ('79', '81', 'NDS', 'Niedersachsen');
INSERT INTO `zones` VALUES ('80', '81', 'BAW', 'Baden-Württemberg');
INSERT INTO `zones` VALUES ('81', '81', 'BAY', 'Bayern');
INSERT INTO `zones` VALUES ('82', '81', 'BER', 'Berlin');
INSERT INTO `zones` VALUES ('83', '81', 'BRG', 'Brandenburg');
INSERT INTO `zones` VALUES ('84', '81', 'BRE', 'Bremen');
INSERT INTO `zones` VALUES ('85', '81', 'HAM', 'Hamburg');
INSERT INTO `zones` VALUES ('86', '81', 'HES', 'Hessen');
INSERT INTO `zones` VALUES ('87', '81', 'MEC', 'Mecklenburg-Vorpommern');
INSERT INTO `zones` VALUES ('88', '81', 'NRW', 'Nordrhein-Westfalen');
INSERT INTO `zones` VALUES ('89', '81', 'RHE', 'Rheinland-Pfalz');
INSERT INTO `zones` VALUES ('90', '81', 'SAR', 'Saarland');
INSERT INTO `zones` VALUES ('91', '81', 'SAS', 'Sachsen');
INSERT INTO `zones` VALUES ('92', '81', 'SAC', 'Sachsen-Anhalt');
INSERT INTO `zones` VALUES ('93', '81', 'SCN', 'Schleswig-Holstein');
INSERT INTO `zones` VALUES ('94', '81', 'THE', 'Thüringen');
INSERT INTO `zones` VALUES ('95', '14', 'WI', 'Wien');
INSERT INTO `zones` VALUES ('96', '14', 'NO', 'Niederösterreich');
INSERT INTO `zones` VALUES ('97', '14', 'OO', 'Oberösterreich');
INSERT INTO `zones` VALUES ('98', '14', 'SB', 'Salzburg');
INSERT INTO `zones` VALUES ('99', '14', 'KN', 'Kärnten');
INSERT INTO `zones` VALUES ('100', '14', 'ST', 'Steiermark');
INSERT INTO `zones` VALUES ('101', '14', 'TI', 'Tirol');
INSERT INTO `zones` VALUES ('102', '14', 'BL', 'Burgenland');
INSERT INTO `zones` VALUES ('103', '14', 'VB', 'Voralberg');
INSERT INTO `zones` VALUES ('104', '204', 'AG', 'Aargau');
INSERT INTO `zones` VALUES ('105', '204', 'AI', 'Appenzell Innerrhoden');
INSERT INTO `zones` VALUES ('106', '204', 'AR', 'Appenzell Ausserrhoden');
INSERT INTO `zones` VALUES ('107', '204', 'BE', 'Bern');
INSERT INTO `zones` VALUES ('108', '204', 'BL', 'Basel-Landschaft');
INSERT INTO `zones` VALUES ('109', '204', 'BS', 'Basel-Stadt');
INSERT INTO `zones` VALUES ('110', '204', 'FR', 'Freiburg');
INSERT INTO `zones` VALUES ('111', '204', 'GE', 'Genf');
INSERT INTO `zones` VALUES ('112', '204', 'GL', 'Glarus');
INSERT INTO `zones` VALUES ('113', '204', 'JU', 'Graubnden');
INSERT INTO `zones` VALUES ('114', '204', 'JU', 'Jura');
INSERT INTO `zones` VALUES ('115', '204', 'LU', 'Luzern');
INSERT INTO `zones` VALUES ('116', '204', 'NE', 'Neuenburg');
INSERT INTO `zones` VALUES ('117', '204', 'NW', 'Nidwalden');
INSERT INTO `zones` VALUES ('118', '204', 'OW', 'Obwalden');
INSERT INTO `zones` VALUES ('119', '204', 'SG', 'St. Gallen');
INSERT INTO `zones` VALUES ('120', '204', 'SH', 'Schaffhausen');
INSERT INTO `zones` VALUES ('121', '204', 'SO', 'Solothurn');
INSERT INTO `zones` VALUES ('122', '204', 'SZ', 'Schwyz');
INSERT INTO `zones` VALUES ('123', '204', 'TG', 'Thurgau');
INSERT INTO `zones` VALUES ('124', '204', 'TI', 'Tessin');
INSERT INTO `zones` VALUES ('125', '204', 'UR', 'Uri');
INSERT INTO `zones` VALUES ('126', '204', 'VD', 'Waadt');
INSERT INTO `zones` VALUES ('127', '204', 'VS', 'Wallis');
INSERT INTO `zones` VALUES ('128', '204', 'ZG', 'Zug');
INSERT INTO `zones` VALUES ('129', '204', 'ZH', 'Zürich');
INSERT INTO `zones` VALUES ('130', '195', 'A Coruña', 'A Coruña');
INSERT INTO `zones` VALUES ('131', '195', 'Álava', 'Álava');
INSERT INTO `zones` VALUES ('132', '195', 'Albacete', 'Albacete');
INSERT INTO `zones` VALUES ('133', '195', 'Alicante', 'Alicante');
INSERT INTO `zones` VALUES ('134', '195', 'Almería', 'Almería');
INSERT INTO `zones` VALUES ('135', '195', 'Asturias', 'Asturias');
INSERT INTO `zones` VALUES ('136', '195', 'Ávila', 'Ávila');
INSERT INTO `zones` VALUES ('137', '195', 'Badajoz', 'Badajoz');
INSERT INTO `zones` VALUES ('138', '195', 'Baleares', 'Baleares');
INSERT INTO `zones` VALUES ('139', '195', 'Barcelona', 'Barcelona');
INSERT INTO `zones` VALUES ('140', '195', 'Burgos', 'Burgos');
INSERT INTO `zones` VALUES ('141', '195', 'Cáceres', 'Cáceres');
INSERT INTO `zones` VALUES ('142', '195', 'Cádiz', 'Cádiz');
INSERT INTO `zones` VALUES ('143', '195', 'Cantabria', 'Cantabria');
INSERT INTO `zones` VALUES ('144', '195', 'Castellón', 'Castellón');
INSERT INTO `zones` VALUES ('145', '195', 'Ceuta', 'Ceuta');
INSERT INTO `zones` VALUES ('146', '195', 'Ciudad Real', 'Ciudad Real');
INSERT INTO `zones` VALUES ('147', '195', 'Córdoba', 'Córdoba');
INSERT INTO `zones` VALUES ('148', '195', 'Cuenca', 'Cuenca');
INSERT INTO `zones` VALUES ('149', '195', 'Girona', 'Girona');
INSERT INTO `zones` VALUES ('150', '195', 'Granada', 'Granada');
INSERT INTO `zones` VALUES ('151', '195', 'Guadalajara', 'Guadalajara');
INSERT INTO `zones` VALUES ('152', '195', 'Guipúzcoa', 'Guipúzcoa');
INSERT INTO `zones` VALUES ('153', '195', 'Huelva', 'Huelva');
INSERT INTO `zones` VALUES ('154', '195', 'Huesca', 'Huesca');
INSERT INTO `zones` VALUES ('155', '195', 'Jaén', 'Jaén');
INSERT INTO `zones` VALUES ('156', '195', 'La Rioja', 'La Rioja');
INSERT INTO `zones` VALUES ('157', '195', 'Las Palmas', 'Las Palmas');
INSERT INTO `zones` VALUES ('158', '195', 'León', 'León');
INSERT INTO `zones` VALUES ('159', '195', 'Lérida', 'Lérida');
INSERT INTO `zones` VALUES ('160', '195', 'Lugo', 'Lugo');
INSERT INTO `zones` VALUES ('161', '195', 'Madrid', 'Madrid');
INSERT INTO `zones` VALUES ('162', '195', 'Málaga', 'Málaga');
INSERT INTO `zones` VALUES ('163', '195', 'Melilla', 'Melilla');
INSERT INTO `zones` VALUES ('164', '195', 'Murcia', 'Murcia');
INSERT INTO `zones` VALUES ('165', '195', 'Navarra', 'Navarra');
INSERT INTO `zones` VALUES ('166', '195', 'Ourense', 'Ourense');
INSERT INTO `zones` VALUES ('167', '195', 'Palencia', 'Palencia');
INSERT INTO `zones` VALUES ('168', '195', 'Pontevedra', 'Pontevedra');
INSERT INTO `zones` VALUES ('169', '195', 'Salamanca', 'Salamanca');
INSERT INTO `zones` VALUES ('170', '195', 'Santa Cruz de Tenerife', 'Santa Cruz de Tenerife');
INSERT INTO `zones` VALUES ('171', '195', 'Segovia', 'Segovia');
INSERT INTO `zones` VALUES ('172', '195', 'Sevilla', 'Sevilla');
INSERT INTO `zones` VALUES ('173', '195', 'Soria', 'Soria');
INSERT INTO `zones` VALUES ('174', '195', 'Tarragona', 'Tarragona');
INSERT INTO `zones` VALUES ('175', '195', 'Teruel', 'Teruel');
INSERT INTO `zones` VALUES ('176', '195', 'Toledo', 'Toledo');
INSERT INTO `zones` VALUES ('177', '195', 'Valencia', 'Valencia');
INSERT INTO `zones` VALUES ('178', '195', 'Valladolid', 'Valladolid');
INSERT INTO `zones` VALUES ('179', '195', 'Vizcaya', 'Vizcaya');
INSERT INTO `zones` VALUES ('180', '195', 'Zamora', 'Zamora');
INSERT INTO `zones` VALUES ('181', '195', 'Zaragoza', 'Zaragoza');
INSERT INTO `zones` VALUES ('182', '13', 'ACT', 'Australian Capital Territory');
INSERT INTO `zones` VALUES ('183', '13', 'NSW', 'New South Wales');
INSERT INTO `zones` VALUES ('184', '13', 'NT', 'Northern Territory');
INSERT INTO `zones` VALUES ('185', '13', 'QLD', 'Queensland');
INSERT INTO `zones` VALUES ('186', '13', 'SA', 'South Australia');
INSERT INTO `zones` VALUES ('187', '13', 'TAS', 'Tasmania');
INSERT INTO `zones` VALUES ('188', '13', 'VIC', 'Victoria');
INSERT INTO `zones` VALUES ('189', '13', 'WA', 'Western Australia');
INSERT INTO `zones` VALUES ('190', '105', 'AG', 'Agrigento');
INSERT INTO `zones` VALUES ('191', '105', 'AL', 'Alessandria');
INSERT INTO `zones` VALUES ('192', '105', 'AN', 'Ancona');
INSERT INTO `zones` VALUES ('193', '105', 'AO', 'Aosta');
INSERT INTO `zones` VALUES ('194', '105', 'AR', 'Arezzo');
INSERT INTO `zones` VALUES ('195', '105', 'AP', 'Ascoli Piceno');
INSERT INTO `zones` VALUES ('196', '105', 'AT', 'Asti');
INSERT INTO `zones` VALUES ('197', '105', 'AV', 'Avellino');
INSERT INTO `zones` VALUES ('198', '105', 'BA', 'Bari');
INSERT INTO `zones` VALUES ('199', '105', 'BT', 'Barletta Andria Trani');
INSERT INTO `zones` VALUES ('200', '105', 'BL', 'Belluno');
INSERT INTO `zones` VALUES ('201', '105', 'BN', 'Benevento');
INSERT INTO `zones` VALUES ('202', '105', 'BG', 'Bergamo');
INSERT INTO `zones` VALUES ('203', '105', 'BI', 'Biella');
INSERT INTO `zones` VALUES ('204', '105', 'BO', 'Bologna');
INSERT INTO `zones` VALUES ('205', '105', 'BZ', 'Bolzano');
INSERT INTO `zones` VALUES ('206', '105', 'BS', 'Brescia');
INSERT INTO `zones` VALUES ('207', '105', 'BR', 'Brindisi');
INSERT INTO `zones` VALUES ('208', '105', 'CA', 'Cagliari');
INSERT INTO `zones` VALUES ('209', '105', 'CL', 'Caltanissetta');
INSERT INTO `zones` VALUES ('210', '105', 'CB', 'Campobasso');
INSERT INTO `zones` VALUES ('211', '105', 'CI', 'Carbonia-Iglesias');
INSERT INTO `zones` VALUES ('212', '105', 'CE', 'Caserta');
INSERT INTO `zones` VALUES ('213', '105', 'CT', 'Catania');
INSERT INTO `zones` VALUES ('214', '105', 'CZ', 'Catanzaro');
INSERT INTO `zones` VALUES ('215', '105', 'CH', 'Chieti');
INSERT INTO `zones` VALUES ('216', '105', 'CO', 'Como');
INSERT INTO `zones` VALUES ('217', '105', 'CS', 'Cosenza');
INSERT INTO `zones` VALUES ('218', '105', 'CR', 'Cremona');
INSERT INTO `zones` VALUES ('219', '105', 'KR', 'Crotone');
INSERT INTO `zones` VALUES ('220', '105', 'CN', 'Cuneo');
INSERT INTO `zones` VALUES ('221', '105', 'EN', 'Enna');
INSERT INTO `zones` VALUES ('222', '105', 'FM', 'Fermo');
INSERT INTO `zones` VALUES ('223', '105', 'FE', 'Ferrara');
INSERT INTO `zones` VALUES ('224', '105', 'FI', 'Firenze');
INSERT INTO `zones` VALUES ('225', '105', 'FG', 'Foggia');
INSERT INTO `zones` VALUES ('226', '105', 'FC', 'Forlì Cesena');
INSERT INTO `zones` VALUES ('227', '105', 'FR', 'Frosinone');
INSERT INTO `zones` VALUES ('228', '105', 'GE', 'Genova');
INSERT INTO `zones` VALUES ('229', '105', 'GO', 'Gorizia');
INSERT INTO `zones` VALUES ('230', '105', 'GR', 'Grosseto');
INSERT INTO `zones` VALUES ('231', '105', 'IM', 'Imperia');
INSERT INTO `zones` VALUES ('232', '105', 'IS', 'Isernia');
INSERT INTO `zones` VALUES ('233', '105', 'AQ', 'Aquila');
INSERT INTO `zones` VALUES ('234', '105', 'SP', 'La Spezia');
INSERT INTO `zones` VALUES ('235', '105', 'LT', 'Latina');
INSERT INTO `zones` VALUES ('236', '105', 'LE', 'Lecce');
INSERT INTO `zones` VALUES ('237', '105', 'LC', 'Lecco');
INSERT INTO `zones` VALUES ('238', '105', 'LI', 'Livorno');
INSERT INTO `zones` VALUES ('239', '105', 'LO', 'Lodi');
INSERT INTO `zones` VALUES ('240', '105', 'LU', 'Lucca');
INSERT INTO `zones` VALUES ('241', '105', 'MC', 'Macerata');
INSERT INTO `zones` VALUES ('242', '105', 'MN', 'Mantova');
INSERT INTO `zones` VALUES ('243', '105', 'MS', 'Massa Carrara');
INSERT INTO `zones` VALUES ('244', '105', 'MT', 'Matera');
INSERT INTO `zones` VALUES ('245', '105', 'VS', 'Medio Campidano');
INSERT INTO `zones` VALUES ('246', '105', 'ME', 'Messina');
INSERT INTO `zones` VALUES ('247', '105', 'MI', 'Milano');
INSERT INTO `zones` VALUES ('248', '105', 'MO', 'Modena');
INSERT INTO `zones` VALUES ('249', '105', 'MB', 'Monza e Brianza');
INSERT INTO `zones` VALUES ('250', '105', 'NA', 'Napoli');
INSERT INTO `zones` VALUES ('251', '105', 'NO', 'Novara');
INSERT INTO `zones` VALUES ('252', '105', 'NU', 'Nuoro');
INSERT INTO `zones` VALUES ('253', '105', 'OG', 'Ogliastra');
INSERT INTO `zones` VALUES ('254', '105', 'OT', 'Olbia-Tempio');
INSERT INTO `zones` VALUES ('255', '105', 'OR', 'Oristano');
INSERT INTO `zones` VALUES ('256', '105', 'PD', 'Padova');
INSERT INTO `zones` VALUES ('257', '105', 'PA', 'Palermo');
INSERT INTO `zones` VALUES ('258', '105', 'PR', 'Parma');
INSERT INTO `zones` VALUES ('259', '105', 'PG', 'Perugia');
INSERT INTO `zones` VALUES ('260', '105', 'PV', 'Pavia');
INSERT INTO `zones` VALUES ('261', '105', 'PU', 'Pesaro Urbino');
INSERT INTO `zones` VALUES ('262', '105', 'PE', 'Pescara');
INSERT INTO `zones` VALUES ('263', '105', 'PC', 'Piacenza');
INSERT INTO `zones` VALUES ('264', '105', 'PI', 'Pisa');
INSERT INTO `zones` VALUES ('265', '105', 'PT', 'Pistoia');
INSERT INTO `zones` VALUES ('266', '105', 'PN', 'Pordenone');
INSERT INTO `zones` VALUES ('267', '105', 'PZ', 'Potenza');
INSERT INTO `zones` VALUES ('268', '105', 'PO', 'Prato');
INSERT INTO `zones` VALUES ('269', '105', 'RG', 'Ragusa');
INSERT INTO `zones` VALUES ('270', '105', 'RA', 'Ravenna');
INSERT INTO `zones` VALUES ('271', '105', 'RC', 'Reggio Calabria');
INSERT INTO `zones` VALUES ('272', '105', 'RE', 'Reggio Emilia');
INSERT INTO `zones` VALUES ('273', '105', 'RI', 'Rieti');
INSERT INTO `zones` VALUES ('274', '105', 'RN', 'Rimini');
INSERT INTO `zones` VALUES ('275', '105', 'RM', 'Roma');
INSERT INTO `zones` VALUES ('276', '105', 'RO', 'Rovigo');
INSERT INTO `zones` VALUES ('277', '105', 'SA', 'Salerno');
INSERT INTO `zones` VALUES ('278', '105', 'SS', 'Sassari');
INSERT INTO `zones` VALUES ('279', '105', 'SV', 'Savona');
INSERT INTO `zones` VALUES ('280', '105', 'SI', 'Siena');
INSERT INTO `zones` VALUES ('281', '105', 'SR', 'Siracusa');
INSERT INTO `zones` VALUES ('282', '105', 'SO', 'Sondrio');
INSERT INTO `zones` VALUES ('283', '105', 'TA', 'Taranto');
INSERT INTO `zones` VALUES ('284', '105', 'TE', 'Teramo');
INSERT INTO `zones` VALUES ('285', '105', 'TR', 'Terni');
INSERT INTO `zones` VALUES ('286', '105', 'TO', 'Torino');
INSERT INTO `zones` VALUES ('287', '105', 'TP', 'Trapani');
INSERT INTO `zones` VALUES ('288', '105', 'TN', 'Trento');
INSERT INTO `zones` VALUES ('289', '105', 'TV', 'Treviso');
INSERT INTO `zones` VALUES ('290', '105', 'TS', 'Trieste');
INSERT INTO `zones` VALUES ('291', '105', 'UD', 'Udine');
INSERT INTO `zones` VALUES ('292', '105', 'VA', 'Varese');
INSERT INTO `zones` VALUES ('293', '105', 'VE', 'Venezia');
INSERT INTO `zones` VALUES ('294', '105', 'VB', 'Verbania');
INSERT INTO `zones` VALUES ('295', '105', 'VC', 'Vercelli');
INSERT INTO `zones` VALUES ('296', '105', 'VR', 'Verona');
INSERT INTO `zones` VALUES ('297', '105', 'VV', 'Vibo Valentia');
INSERT INTO `zones` VALUES ('298', '105', 'VI', 'Vicenza');
INSERT INTO `zones` VALUES ('299', '105', 'VT', 'Viterbo');
